redis:
    master:
        extraEnvVars:
            - name: FOO
              value: ENC[AES256_GCM,data:n91jyUJ1,iv:po9ZHkV5Vw9dXZ9gtPf0xyb92C49tVSBFZ7K1DvFghI=,tag:/RY3zC4vPZQTKegF3VDIvg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/iceo-dev/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-08-10T13:41:37Z"
          enc: CiQAT06W8r44b18uUyAh+SQDexH6h7q/RUNfhT0k7ZYJ2KpmKxYSYyphChQKDNXBMdotWVolW630MxDz9v6FChIwCigJHJkFT4RA4UvdKJ7Yi+Zv/o0M7o2dhHoCVgkZrKP3yQwBZbidh9T+EO7f+a4DGhcKEGIglxnOyfC6J3f8RNtPR9oQso77bA==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-10T13:41:37Z"
    mac: ENC[AES256_GCM,data:iznNnE25ZVH2vRA+hSsLjvGB0HqffATQeMjSHTj9+ipVQlF7phbI0xchl+m1zgSEzS1I1xRp//ZD1mdEPKe33Z7unsFkM+Gt40ky3/NqS7WApClvBbfOOIVSsdIGSzWdmUWfd4RRgwpolwJT416fUiJpyS2yNwF3YeYlCt0+k2s=,iv:46+zZg5ojDYXyGccSlpPauDHqqjA3yfDxeoqTIqgr1I=,tag:RHFlzx/JK2klHeEtXf6UVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|value)$
    version: 3.7.3
