app:
    password: ENC[AES256_GCM,data:hxXEXeDLaiZq,iv:HN+9HZWrvNuBmWD08oKxvR8ABR9nK8KBfXTYjuxTdzg=,tag:RLPXcHlIJK4FHrfNS8y6YA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/iceo-dev/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-08-10T09:24:06Z"
          enc: CiQAT06W8vmo3YSnNxF2ps82se/nHaxdMxvVGE029cSAm4LE+7gSZCpiChQKDOILvhSwKSNkcgeTKhDRhv7iBBIwCigyStwfgeoYfLkg1qEGxNmQZxS1MNwFNheezdMg8AwtqWXEBvsP9BDBENPMq/kKGhgKEJkIfdkLFCI/O07Pk/05hnoQiYmV6ws=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-10T09:24:07Z"
    mac: ENC[AES256_GCM,data:46gc7hFoQ44GObWagAm2LUPK23nil2oLsR4Lg8stUtPNcMl1jzEJHvia1AWcmcEUraUuqWQn5NmzzIzJ0QZZ9Um0/AhUsZt4ZXiUjemahIwomkoW2d3G7RXdeu2exbmM2s1ssD2FPBgwG5PMIU8qAaD7dQKu5FxiHGDhtl88DI8=,iv:ayeNpJT3yjcSRb9csf70pACnZ34lX6SxdjNU3aN5kMQ=,tag:uke7moH8OKBfvMZJGmnmVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password)$
    version: 3.7.3
